---
- name: Install apt repository
  when: ansible_os_family == "Debian"
  block:
    - name: Install package requirements
      ansible.builtin.package:
        name:
          - gnupg
          - apt-transport-https
        state: present

    - name: Install elastic apt repo key
        ansible.builtin.apt_key:
          url: "{{ elastic_repo_gpg_key }}"
          state: "{{ elastic_repo_state }}"

    - name: Install elastic apt repository (elastic license)
      ansible.builtin.apt_repository:
        repo: "{{ _elastic_repo_url_els }}"
        filename: elastic
        state: "{{ elastic_repo_state }}"
      when: not elastic_repo_oss | bool

    - name: Install elastic apt repository (oss license)
      ansible.builtin.apt_repository:
        repo: "{{ _elastic_repo_url_oss }}"
        filename: elastic
        state: "{{ elastic_repo_state }}"
      when: elastic_repo_oss | bool

- name: Install yum repository
  when: (ansible_os_family | lower) == 'redhat'
  block:

    - name: install elastic yum repo key
      ansible.builtin.rpm_key:
        key: "{{ elastic_repo_gpg_key }}"
        state: "{{ elastic_repo_state }}"

    - name: install elastic yum repository (elastic license)
      ansible.builtin.yum_repository:
        name: elastic
        description: "Elastic package repository"
        baseurl: "{{ _elastic_repo_url_els }}"
        enabled: yes
        gpgcheck: yes
        gpgkey: "{{ elastic_repo_gpg_key }}"
      when: not (elastic_repo_oss | bool)

    - name: install elastic yum repository (oss license)
      ansible.builtin.yum_repository:
        name: elastic
        description: "Elastic package repository"
        baseurl: "{{ _elastic_repo_url_oss }}"
        enabled: yes
        gpgcheck: yes
        gpgkey: "{{ elastic_repo_gpg_key }}"
      when: elastic_repo_oss | bool
