---
- name: set variable overrides
  set_fact:
    _elastic_repo_packages: "{{ elastic_repo_packages | default(elastic_repo_packages_default | sorted_get(overrides)) }}"
    _elastic_repo_url_els: "{{ elastic_repo_url | default(elastic_repo_url_default_els | sorted_get(overrides)) }}"
    _elastic_repo_url_oss: "{{ elastic_repo_url | default(elastic_repo_url_default_oss | sorted_get(overrides)) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
  tags:
    - always

- name: install package requirements
  package:
    name: "{{ _elastic_repo_packages | default(elastic_repo_package_name_default) }}"
    state: present
  when: _elastic_repo_packages != []

- block:

    - name: install elastic apt repo key
      apt_key:
        url: "{{ elastic_repo_gpg_key }}"
        state: "{{ elastic_repo_state }}"

    - name: install elastic apt repository (elastic license)
      apt_repository:
        repo: "{{ _elastic_repo_url_els }}"
        filename: elastic
        state: "{{ elastic_repo_state }}"
      when: not (elastic_repo_oss | bool)

    - name: install elastic apt repository (oss license)
      apt_repository:
        repo: "{{ _elastic_repo_url_oss }}"
        filename: elastic
        state: "{{ elastic_repo_state }}"
      when: elastic_repo_oss | bool

  when: (ansible_os_family | lower) == 'debian'

- block:

    - name: install elastic yum repo key
      rpm_key:
        key: "{{ elastic_repo_gpg_key }}"
        state: "{{ elastic_repo_state }}"

    - name: install elastic yum repository (elastic license)
      yum_repository:
        name: elastic
        description: "Elastic package repository"
        baseurl: "{{ _elastic_repo_url_els }}"
        enabled: yes
        gpgcheck: yes
        gpgkey: "{{ elastic_repo_gpg_key }}"
      when: not (elastic_repo_oss | bool)

    - name: install elastic yum repository (oss license)
      yum_repository:
        name: elastic
        description: "Elastic package repository"
        baseurl: "{{ _elastic_repo_url_oss }}"
        enabled: yes
        gpgcheck: yes
        gpgkey: "{{ elastic_repo_gpg_key }}"
      when: elastic_repo_oss | bool

  when: (ansible_os_family | lower) == 'redhat'
