---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: stretch
    image: debian:stretch
  - name: centos7
    image: centos:7
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
