---
name: molecule

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: "nephelaiio.elastic_repo"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
          - elastic
        release:
          - 7
          - 8
          - 9
        include:
          - image: ubuntu2204
            command: /lib/systemd/systemd
          - image: ubuntu2004
            command: /lib/systemd/systemd
          - image: debian12
            command: /lib/systemd/systemd
          - image: debian11
            command: /lib/systemd/systemd
          - image: rockylinux9
            command: /usr/lib/systemd/systemd
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.elastic_repo"

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true
          project-path: "nephelaiio.elastic_repo"

      - name: Install test requirements
        run: devbox run -- make install

      - name: Debug test environment
        run: devbox run -- make debug

      - name: Run molecule tests.
        run: devbox run -- make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
          MOLECULE_ELASTICSEARCH_MAJOR_VERSION: ${{ matrix.release }}
